language: node_js
branches:
  only:
  - master
  - /^release-.*/
cache:
  directories:
    - node_modules
node_js:
  - "8"
install:
  - yarn install --pure-lockfile
script:
  - yarn compile
  - yarn tslint
